spring:
  application:
    name: sample-source

server.port: 9000

##### h2 database properties ####################
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.DriverMetricsInstrumentation
  username: sa
  hikari:
    idle-timeout: 10000
    pool-name: h2-hikari-cp
    minimum-idle: 2
    maximum-pool-size: 5

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.use-new-id-generator-mappings: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.h2.console.enabled: true
spring.h2.console.settings.web-allow-others: true
h2.tcp.enabled: true

#### Generate Schema creation script ###########
#spring.jpa.properties.javax.persistence.schema-generation.create-source: metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action: create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target: create.sql

#### Enable Metrics #############################
management.endpoint.health.show-details: always
management.endpoints.web.exposure.include: health,info,metrics,bindings

#### Kafka Binder properties ####################
spring.cloud.stream.kafka.binder.brokers: vindaloo:9092
spring.cloud.stream.bindings.output.destination: test-data
logging.level.org.springframework.cloud.stream: DEBUG

#### jdbc-source properties #####################
jdbc.query: select * from Item
jdbc.max-rows-per-poll: 10
jdbc.split: false
trigger.cron: 0 0/1 * * * ?
